apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-xkic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-xkic
    app.kubernetes.io/part-of: load-app-49e09ad6-fc63-4206-8e09-77c7b41594b5
  name: devfile-sample-java-springboot-basic-xkic
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-xkic
status:
  loadBalancer: {}
